### ISSUE TITLE
run CameraExample.java error

### ISSUE THREAD

**Issue by shellus** [hoary/JavaAV#5]
run “JavaAV/JavaAV/src/examples/java/com/github/hoary/javaav/CameraExample.java”

java.lang.UnsatisfiedLinkError: no jniavutil in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1865)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:524)
	at org.bytedeco.javacpp.Loader.load(Loader.java:399)
	at org.bytedeco.javacpp.Loader.load(Loader.java:353)
	at org.bytedeco.javacpp.avutil.<clinit>(avutil.java:10)
	at com.github.hoary.javaav.PixelFormat.<clinit>(PixelFormat.java:198)
	at com.github.hoary.javaav.Image.getPixelFormat(Image.java:52)
	at com.github.hoary.javaav.EncoderTest.testEncoder(EncoderTest.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.UnsatisfiedLinkError: /private/var/folders/lz/mhx6k79d3kb4zss3qwc2s3h00000gn/T/javacpp46847350391384/libjniavutil.dylib: dlopen(/private/var/folders/lz/mhx6k79d3kb4zss3qwc2s3h00000gn/T/javacpp46847350391384/libjniavutil.dylib, 1): Library not loaded: @rpath/libavutil.52.dylib
  Referenced from: /private/var/folders/lz/mhx6k79d3kb4zss3qwc2s3h00000gn/T/javacpp46847350391384/libjniavutil.dylib
  Reason: no suitable image found.  Did find:
	/private/var/folders/lz/mhx6k79d3kb4zss3qwc2s3h00000gn/T/javacpp46847350391384/./libavutil.52.dylib: malformed mach-o image: load command #16 length (0) too small in /private/var/folders/lz/mhx6k79d3kb4zss3qwc2s3h00000gn/T/javacpp46847350391384/./libavutil.52.dylib
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1937)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1822)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:513)
	... 36 more

Process finished with exit code 255

**Comment by baconsword** [comment]
I don't know if this helps but, the error points to the lack of a JNI library.
The library must be in your classpath. Could you check if it is?
